global:
  message: Welcome to order service dev environment!!

server:
  port: 8083

message: Hello from Dev!

spring:
  datasource:
    url: jdbc:h2:mem:order_master
    username: root
    password: Admin@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
